#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh


cp 0.orig  0 -r
runApplication setFields


#runApplication decomposePar

#runParallel `getApplication`
#runApplication reconstructPar

runApplication  `getApplication`
